// <auto-generated />
using DoctorsApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DoctorsApp.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190712032735_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("DoctorsApp.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Gender");

                    b.Property<int>("MedicalSchoolId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("MedicalSchoolId");

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("DoctorsApp.Models.DoctorLanguage", b =>
                {
                    b.Property<int>("DoctorId");

                    b.Property<int>("LanguageId");

                    b.HasKey("DoctorId", "LanguageId");

                    b.HasIndex("LanguageId");

                    b.ToTable("DoctorLanguages");
                });

            modelBuilder.Entity("DoctorsApp.Models.DoctorSpecialty", b =>
                {
                    b.Property<int>("DoctorId");

                    b.Property<int>("SpecialtyId");

                    b.HasKey("DoctorId", "SpecialtyId");

                    b.HasIndex("SpecialtyId");

                    b.ToTable("DoctorSpecialties");
                });

            modelBuilder.Entity("DoctorsApp.Models.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("DoctorsApp.Models.MedicalSchool", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("MedicalSchools");
                });

            modelBuilder.Entity("DoctorsApp.Models.PatientRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Comments");

                    b.Property<int>("DoctorId");

                    b.Property<int>("Rating");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.ToTable("PatientRatings");
                });

            modelBuilder.Entity("DoctorsApp.Models.Specialty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Specialties");
                });

            modelBuilder.Entity("DoctorsApp.Models.Doctor", b =>
                {
                    b.HasOne("DoctorsApp.Models.MedicalSchool", "MedicalSchool")
                        .WithMany()
                        .HasForeignKey("MedicalSchoolId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DoctorsApp.Models.DoctorLanguage", b =>
                {
                    b.HasOne("DoctorsApp.Models.Doctor", "Doctor")
                        .WithMany("DoctorLanguages")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DoctorsApp.Models.Language", "Language")
                        .WithMany("DoctorLanguages")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DoctorsApp.Models.DoctorSpecialty", b =>
                {
                    b.HasOne("DoctorsApp.Models.Doctor", "Doctor")
                        .WithMany("DoctorSpecialties")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DoctorsApp.Models.Specialty", "Specialty")
                        .WithMany("DoctorSpecialties")
                        .HasForeignKey("SpecialtyId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DoctorsApp.Models.PatientRating", b =>
                {
                    b.HasOne("DoctorsApp.Models.Doctor")
                        .WithMany("PatientRatings")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
